#dockerfile for play-activator
FROM openjdk:8u111-jdk-alpine

RUN apk update && apk add bash

ENV PROJECT_HOME /usr/src

RUN mkdir -p $PROJECT_HOME/activator $PROJECT_HOME/app

WORKDIR $PROJECT_HOME/activator

#download and install activator
ENV ACTIVATOR_VERSION 1.3.10
RUN wget http://downloads.typesafe.com/typesafe-activator/$ACTIVATOR_VERSION/typesafe-activator-$ACTIVATOR_VERSION-minimal.zip && \
    unzip typesafe-activator-$ACTIVATOR_VERSION-minimal.zip && \
    rm typesafe-activator-$ACTIVATOR_VERSION-minimal.zip

#make the project binaries available to the container by adding them to $PATH
ENV PATH $PROJECT_HOME/activator/activator-$ACTIVATOR_VERSION-minimal/bin:$PATH

WORKDIR $PROJECT_HOME/app

COPY . ./

RUN activator run && rm -rf $PROJECT_HOME/app