version: '2'
services:
  app:
    build: .
    command: activator run -Dhttp.address=0.0.0.0 -Dhttp.port=4000
    volumes:
      - .:/usr/src/app
    expose:
      - 4000
    ports:
      - 3000:4000
    depends_on:
      - db
    links:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=playdb
